version: '3.9'

networks:
  local-dev:
    name: local-dev-1
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    command: just serve
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - local-dev
    ports:
      - 9202:9202
    volumes:
      - ./cmd:/app/cmd
      - ./config:/app/config
      - ./database:/app/database
      - ./internal:/app/internal
      - ./test:/app/test
      - ./justfile:/app/justfile
      - ./package.json:/app/package.json

  postgres_db:
    image: postgres:14
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_MULTIPLE_DATABASES: svcdb,testdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 20s
      retries: 10
    networks:
      - local-dev
    ports:
      - 25432:5432
    volumes:
      - ./database/scripts:/docker-entrypoint-initdb.d/
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
